TYPE : 'master'
#slave
SERVER_NAME : 'spider5'
MASTER_REQUSET_RETRY_TIME: 10
SLAVE_PORT : 38383
SLAVE_IP :
    'spider1': '120.25.222.158'
    'spider6': '120.25.122.61'
    'spdier7': '112.74.96.190'

E_MAIL_TEMPLATE_PATH : './deadshot/e_mail.html'
DEADSHOT_LOG_PATH : './log/'


# ---------------- SupervisorShoter ----------------
# 不在次列表中的,都被视为异常状态
SUPERVISOR_NORMAL_STATUS :
    - 'RUNNING'

SUPERVISOR_FILTERED_NAME :
    - 'teddywalker_RL0069'

# ---------------- RetryShoter ----------------
RETRY_LOG_PATH : './test_data/spider/'
RETRY_LOG_FILTER_DIR :
    - '_info$'

RETRY_LOG_FILTER_FILE :
    - '_info.log$'

RETRY_LAST_LINES : 500
RETRY_MAX_COUNT: 500

# 最大通知时间，在这之后的retry会发送邮件通知
RETRY_MAX_TIME : 999999999

RETRY_PATTERN :
    'retry': '\[(.+?)\]\[(.+?)\] \[Retry\]'
    'process': '\[(.+?)\]\[(.+?)\] \[process\]'

# ---------------- UnknownShoter ------------------
UNKNOWN_LOG_PATH : '/mnt/octopus/log/_unknown'
# 最大通知时间，在这之后的unknown会发送邮件通知
UNKNOWN_MAX_TIME : 3600
UNKNOWN_PATTERN :
    'unknow': '\[(.+?)\]\[(.+?)\]'

# ----------------- SendEmail --------------------
PRIVATE_KEY : ''
TEMPLATE_NAME : ''
EMAIL_API_URL : ''
